CREATE TABLE STUDIES(PNAME VARCHAR(20), INSTITUTE VARCHAR(20), COURSE VARCHAR(10), COURSEFEE NUMBER(5));

INSERT INTO STUDIES VALUES('ANAND', 'SABHARI', 'PGDCA', 4500);
INSERT INTO STUDIES VALUES('&PNAME', '&INSTITUTE', '&COURSE', '&COURSEFEE');
SELECT * FROM STUDIES;

CREATE TABLE SOFTWARE(PNAME VARCHAR(20), TITLE VARCHAR(20), DEVELOPING VARCHAR(10), SCOST NUMBER(10), DCOST NUMBER(10), SOLD NUMBER(3));
INSERT INTO SOFTWARE VALUES('&PNAME', '&TITLE', '&DEVELOPING', '&SCOST', '&DCOST', '&SOLD');
SELECT * FROM SOFTWARE;

CREATE TABLE PROGRAMMER(PNAME VARCHAR(20), DOB DATE, DOJ DATE, SEX CHAR(1), PROF1 VARCHAR(10), PROF2 VARCHAR(10), SALARY NUMBER(10));
INSERT INTO PROGRAMMER VALUES('&PNAME', '&DOB', '&DOJ', '&SEX', '&PROF1', '&PROF2', '&SALARY');
SELECT * FROM PROGRAMMER;
DELETE FROM PROGRAMMER WHERE PNAME= null;

